blueprint:
  name: Zigbee2MQTT - Zemismart ZM-RM02 Smart 6 key scene switch
  description: Automate your Zemismart ZM-RM02 Smart 6 key scene switch via Zigbee2MQTT.
  domain: automation
  input:
    switch:
      name: ZM-RM02 Smart 6 key scene switch
      description: ZM-RM02 Smart 6 key scene switch to use
      selector:
        entity:
          integration: mqtt
          domain: sensor
    button_one_short_press:
      name: Single Press - Button 1
      description: Action to run on button 1 single press
      default: []
      selector:
        action: {}
    button_one_double_press:
      name: Double Press - Button 1
      description: Action to run on button 1 double press
      default: []
      selector:
        action: {}
    button_one_long_press:
      name: Long Press - Button 1
      description: Action to run on button 1 long press
      default: []
      selector:
        action: {}
    button_two_short_press:
      name: Single Press - Button 2
      description: Action to run on button 2 single press
      default: []
      selector:
        action: {}
    button_two_double_press:
      name: Double Press - Button 2
      description: Action to run on button 2 double press
      default: []
      selector:
        action: {}
    button_two_long_press:
      name: Long Press - Button 2
      description: Action to run on button 2 long press
      default: []
      selector:
        action: {}
    button_three_short_press:
      name: Single Press - Button 3
      description: Action to run on button 3 single press
      default: []
      selector:
        action: {}
    button_three_double_press:
      name: Double Press - Button 3
      description: Action to run on button 3 double press
      default: []
      selector:
        action: {}
    button_three_long_press:
      name: Long Press - Button 3
      description: Action to run on button 3 long press
      default: []
      selector:
        action: {}
    button_four_short_press:
      name: Single Press - Button 4
      description: Action to run on button 4 single press
      default: []
      selector:
        action: {}
    button_four_double_press:
      name: Double Press - Button 4
      description: Action to run on button 4 double press
      default: []
      selector:
        action: {}
    button_four_long_press:
      name: Long Press - Button 4
      description: Action to run on button 4 long press
      default: []
      selector:
        action: {}
    button_five_short_press:
      name: Single Press - Button 5
      description: Action to run on button 5 single press
      default: []
      selector:
        action: {}
    button_five_double_press:
      name: Double Press - Button 5
      description: Action to run on button 5 double press
      default: []
      selector:
        action: {}
    button_five_long_press:
      name: Long Press - Button 5
      description: Action to run on button 5 long press
      default: []
      selector:
        action: {}
    button_six_short_press:
      name: Single Press - Button 6
      description: Action to run on button 6 single press
      default: []
      selector:
        action: {}
    button_six_double_press:
      name: Double Press - Button 6
      description: Action to run on button 6 double press
      default: []
      selector:
        action: {}
    button_six_long_press:
      name: Long Press - Button 6
      description: Action to run on button 6 long press
      default: []
      selector:
        action: {}
mode: restart
max_exceeded: silent
trigger:
- platform: state
  entity_id: !input "switch"
  attribute: action
action:
- variables:
    command: "{{ trigger.to_state.state }}"
- choose:
  - conditions: 
    - "{{ command == 'button_1_single' }}"
    sequence: !input "button_one_short_press"
  - conditions: 
    - "{{ command == 'button_2_single' }}"
    sequence: !input "button_two_short_press"
  - conditions: 
    - "{{ command == 'button_3_single' }}"
    sequence: !input "button_three_short_press"
  - conditions: 
    - "{{ command == 'button_4_single' }}"
    sequence: !input "button_four_short_press"
  - conditions: 
    - "{{ command == 'button_5_single' }}"
    sequence: !input "button_five_short_press"
  - conditions: 
    - "{{ command == 'button_6_single' }}"
    sequence: !input "button_six_short_press"
  - conditions: 
    - "{{ command == 'button_1_double' }}"
    sequence: !input "button_one_double_press"
  - conditions: 
    - "{{ command == 'button_2_double' }}"
    sequence: !input "button_two_double_press"
  - conditions: 
    - "{{ command == 'button_3_double' }}"
    sequence: !input "button_three_double_press"
  - conditions: 
    - "{{ command == 'button_4_double' }}"
    sequence: !input "button_four_double_press"
  - conditions: 
    - "{{ command == 'button_5_double' }}"
    sequence: !input "button_five_double_press"
  - conditions: 
    - "{{ command == 'button_6_double' }}"
    sequence: !input "button_six_double_press"
  - conditions: 
    - "{{ command == 'button_1_hold' }}"
    sequence: !input "button_one_long_press"
  - conditions: 
    - "{{ command == 'button_2_hold' }}"
    sequence: !input "button_two_long_press"
  - conditions: 
    - "{{ command == 'button_3_hold' }}"
    sequence: !input "button_three_long_press"
  - conditions: 
    - "{{ command == 'button_4_hold' }}"
    sequence: !input "button_four_long_press"
  - conditions: 
    - "{{ command == 'button_5_hold' }}"
    sequence: !input "button_five_long_press"
  - conditions: 
    - "{{ command == 'button_6_hold' }}"
    sequence: !input "button_six_long_press"
